### ISSUE TITLE
where is qualtrics.py?

### ISSUE THREAD

**Issue by scm1210** [matomatical/qualtrics#5]
hi im sorry if ive missed something. ove cloned the repo and am trying to work through your examples but where is qualtrics.py? i cant seem to find it

**Comment by scm1210** [comment]
nvm figured it out!

**Comment by matomatical** [comment]
Thanks for your question, sorry that the documentation is a bit out of date. For future reference, the tool is now a module called `qualtrics` represented by an entire folder rather than a single python script called `qualtrics.py`.
